### ISSUE TITLE
Marqueurs objectifs

### ISSUE THREAD

**Issue by Cl0v1s** [Cl0v1s/AsmR#1]
Il faudrait remplacer les 2 "=" par des triangles pointant vers le bas pour marquer la zone objectif sur la jauge.

I.E: dessiner un triangle de 8x8 qui pointe vers le bas, avec la pointe au milieu des 8 pixels.
Remplacer l'usage des "=" par le nouveau triangle

<img width="309" alt="image" src="https://user-images.githubusercontent.com/917518/101247545-79f97100-371a-11eb-9c2c-6b159a42f7a8.png">

**Comment by tvanhatalo** [comment]
C'est fait
